version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: pizzashop-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: pizzashop
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
      - ./server/pizzashop.sql:/docker-entrypoint-initdb.d/01_pizzashop.sql:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pizzashop-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3001
      JWT_SECRET: supersecretjwtkey
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 12345678
      DB_NAME: pizzashop
    ports:
      - "3001:3001" # App erreichbar unter localhost:3001
    restart: unless-stopped

volumes:
  db_data:
